import { NextResponse } from "next/server";
import { z } from "zod";
import { requireStaff } from "@/lib/security";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const input=z.discriminatedUnion("action",[
  z.object({action:z.literal("payment-method"),name:z.string().trim().min(2).max(80),requiresReference:z.boolean(),allowsProof:z.boolean()}),
  z.object({action:z.literal("marketing-agency"),name:z.string().trim().min(2).max(160),contactName:z.string().trim().max(160).optional(),email:z.string().email().optional().or(z.literal("")),mobile:z.string().trim().max(40).optional()}),
  z.object({action:z.literal("partner"),name:z.string().trim().min(2).max(160),email:z.string().email().optional().or(z.literal("")),mobile:z.string().trim().max(40).optional()}),
  z.object({action:z.literal("course"),id:z.string().uuid().optional(),code:z.string().trim().min(2).max(40),name:z.string().trim().min(2).max(240),categoryId:z.string().uuid(),deliveryType:z.enum(["In-House","Partner or Endorsed"]),durationLabel:z.string().trim().min(2).max(60),durationDays:z.number().positive().max(365),mode:z.string().trim().min(2).max(80),priceCentavos:z.number().int().nonnegative()}),
  z.object({action:z.literal("offer-rate"),id:z.string().uuid(),durationLabel:z.string().trim().min(2).max(60),trainingFeeCentavos:z.number().int().nonnegative(),rebateCentavos:z.number().int().nonnegative()}),
  z.object({action:z.literal("invite-user"),employeeId:z.string().uuid(),completeName:z.string().trim().min(2).max(160),email:z.string().email(),roleCode:z.enum(["admin","registration","cashier","accounting","training_operations","hr","instructor"])}),
]);
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,50);

export async function GET(){const staff=await requireStaff(["admin"]);if(!staff)return NextResponse.json({error:"Admin access required."},{status:403});const db=createSupabaseAdminClient(),results=await Promise.all([db.from("payment_methods").select("*").order("sort_order"),db.from("marketing_agencies").select("*").order("name"),db.from("partner_centers").select("*").order("name"),db.from("courses").select("id,code,name,category_id,delivery_type,duration_label,duration_days,training_mode,standard_price_centavos,active").order("name"),db.from("partner_course_offers").select("id,course_id,partner_center_id,duration_label,training_fee_centavos,rebate_centavos,partner_payable_centavos,partner_centers(name),courses(name)").eq("active",true),db.from("course_categories").select("id,name").eq("active",true).order("sort_order"),db.from("employees").select("id,complete_name,position,work_email,profile_id,active").eq("active",true).order("complete_name")]);const error=results.find(r=>r.error)?.error;if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({paymentMethods:results[0].data,agencies:results[1].data,partners:results[2].data,courses:results[3].data,offers:results[4].data,categories:results[5].data,employees:results[6].data},{headers:{"cache-control":"no-store"}})}

export async function POST(request:Request){const staff=await requireStaff(["admin"]);if(!staff)return NextResponse.json({error:"Admin access required."},{status:403});try{const value=input.parse(await request.json()),db=createSupabaseAdminClient();let record:unknown,recordType=value.action;
  if(value.action==="payment-method"){const {data,error}=await db.from("payment_methods").upsert({code:slug(value.name),name:value.name,requires_reference:value.requiresReference,allows_proof:value.allowsProof,active:true},{onConflict:"code"}).select().single();if(error)throw error;record=data}
  else if(value.action==="marketing-agency"){const {data,error}=await db.from("marketing_agencies").upsert({name:value.name,contact_name:value.contactName||null,email:value.email||null,mobile:value.mobile||null,active:true},{onConflict:"name"}).select().single();if(error)throw error;record=data}
  else if(value.action==="partner"){const {data,error}=await db.from("partner_centers").upsert({name:value.name,contact_details:{email:value.email||null,mobile:value.mobile||null},active:true},{onConflict:"name"}).select().single();if(error)throw error;record=data}
  else if(value.action==="course"){const payload={code:value.code.toUpperCase(),name:value.name,category_id:value.categoryId,delivery_type:value.deliveryType,duration_label:value.durationLabel,duration_days:value.durationDays,training_mode:value.mode,standard_price_centavos:value.priceCentavos,public_visible:value.deliveryType==="In-House",active:true};const query=value.id?db.from("courses").update(payload).eq("id",value.id):db.from("courses").insert(payload);const {data,error}=await query.select().single();if(error)throw error;record=data}
  else if(value.action==="offer-rate"){if(value.rebateCentavos>value.trainingFeeCentavos)throw new Error("Rebate cannot exceed the training fee.");const {data,error}=await db.from("partner_course_offers").update({duration_label:value.durationLabel,training_fee_centavos:value.trainingFeeCentavos,rebate_centavos:value.rebateCentavos,updated_at:new Date().toISOString()}).eq("id",value.id).select().single();if(error)throw error;record=data}
  else {const invitation=await db.auth.admin.inviteUserByEmail(value.email,{data:{complete_name:value.completeName},redirectTo:`${process.env.APP_BASE_URL??"http://localhost:3000"}/auth/callback?next=/portal`});if(invitation.error||!invitation.data.user)throw invitation.error??new Error("Account invitation failed.");const user=invitation.data.user;await db.from("profiles").upsert({id:user.id,email:value.email,complete_name:value.completeName,account_state:"Invited"});const {data:role}=await db.from("roles").select("id").eq("code",value.roleCode).single();if(!role)throw new Error("Role not found.");await db.from("user_roles").upsert({user_id:user.id,role_id:role.id,assigned_by:staff.user.id});await db.from("employees").update({profile_id:user.id,work_email:value.email}).eq("id",value.employeeId);record={userId:user.id,email:value.email,role:value.roleCode}}
  await db.from("audit_logs").insert({actor_id:staff.user.id,actor_role:"admin",action:`configuration.${value.action}`,record_type:recordType,record_id:crypto.randomUUID(),new_values:record});return NextResponse.json({ok:true,record});
}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Configuration could not be saved."},{status:400})}}
