"use client";
import { FormEvent,useEffect,useState } from "react";

type Data={paymentMethods:{id:string;name:string;requires_reference:boolean}[];agencies:{id:string;name:string}[];partners:{id:string;name:string}[];courses:{id:string;code:string;name:string;category_id:string;delivery_type:"In-House"|"Partner or Endorsed";duration_label:string;duration_days:number;training_mode:string;standard_price_centavos:number}[];offers:{id:string;duration_label:string;training_fee_centavos:number;rebate_centavos:number;partner_centers?:{name:string}|{name:string}[];courses?:{name:string}|{name:string}[]}[];categories:{id:string;name:string}[];employees:{id:string;complete_name:string;position:string;work_email?:string|null;profile_id?:string|null}[];users:{id:string;email:string;completeName:string;accountState:string;roles:string[];position:string|null}[]};
const ROLE_OPTIONS:[string,string][]=[["admin","Admin"],["registration","Registration"],["cashier","Cashier"],["accounting","Accounting"],["training_operations","Training Operations"],["hr","HR"],["instructor","Instructor"]];
const one=<T,>(v:T|T[]|null|undefined)=>Array.isArray(v)?v[0]:v;
export function AdminConfiguration(){const [data,setData]=useState<Data|null>(null),[section,setSection]=useState("users"),[message,setMessage]=useState(""),[debug,setDebug]=useState<{userId:string|null;email:string|null;roles:string[]}|undefined>();async function load(){const response=await fetch("/api/admin/configuration",{cache:"no-store"}),body=await response.json();if(response.ok)setData(body);else{setMessage(body.error);setDebug(body.debug)}}useEffect(()=>{void load()},[]);async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");const form=new FormData(event.currentTarget),payload=JSON.parse(String(form.get("payload"))) as Record<string,unknown>;for(const [key,value] of form.entries())if(key!=="payload")payload[key]=value;for(const key of ["requiresReference","allowsProof"])if(key in payload)payload[key]=form.get(key)==="on";for(const key of ["priceCentavos","trainingFeeCentavos","rebateCentavos"])if(key in payload)payload[key]=Math.round(Number(form.get(key))*100);if("durationDays" in payload)payload.durationDays=Number(form.get("durationDays"));const response=await fetch("/api/admin/configuration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();setMessage(response.ok?"Saved successfully.":body.error??"Could not save.");if(response.ok){event.currentTarget.reset();await load()}}
  if(!data)return <div className="empty-state portal-panel"><span>{message?"⛔":"⚙"}</span><h2>{message?"Can’t load Admin configuration":"Loading Admin configuration…"}</h2><p>{message?(/admin access/i.test(message)?"Your account is signed in but does not have the Admin role. Ask a system administrator to grant it, or set it in Supabase.":message):"Please wait…"}</p>{debug&&<div style={{marginTop:14,padding:"12px 14px",background:"#f4f8fa",border:"1px solid #dbe7ec",borderRadius:8,textAlign:"left",fontSize:12,color:"#405d70",maxWidth:520,marginLeft:"auto",marginRight:"auto"}}><strong style={{display:"block",marginBottom:6}}>Diagnostics for support</strong><div>Signed in as: <code>{debug.email??"— no session —"}</code></div><div>User ID: <code>{debug.userId??"— none —"}</code></div><div>Roles in database: <code>{debug.roles.length?debug.roles.join(", "):"— none —"}</code></div><div style={{marginTop:6,fontSize:11,color:"#6d8492"}}>{!debug.userId?"No active session was detected — sign in again.":debug.roles.includes("admin")?"Admin role IS present — refresh the page; if this persists, report it.":"This account has no admin role. Grant admin to this exact User ID in Supabase."}</div></div>}</div>;
  const tabs=["users","payment modes","partners","marketing agencies","courses","endorsed rates"];
  return <div className="admin-config"><div className="segment config-tabs">{tabs.map(tab=><button key={tab} className={section===tab?"active":""} onClick={()=>{setSection(tab);setMessage("")}}>{tab}</button>)}</div>{message&&<p className="form-message">{message}</p>}
    {section==="users"&&<ConfigForm title="Create a new user account" text="Creates the login (email + password) AND assigns the portal role in one step — no Supabase dashboard needed. Share the temporary password with the user; they can change it later from the sign-in page. The password is used only to create the account and is never stored by the portal." onSubmit={save} payload={{action:"create-user"}}><label>Complete name<input name="completeName" required/></label><label>Email<input name="email" type="email" required/></label><label>Temporary password<input name="password" type="text" required minLength={6} placeholder="At least 6 characters"/></label><label>Position<input name="position" placeholder="e.g. Cashier (optional)"/></label><label>Role<select name="roleCode">{ROLE_OPTIONS.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label></ConfigForm>}
    {section==="users"&&<ConfigForm title="Add or change a user by email" text="Already have a Supabase login (or created one in the dashboard)? Assign or change its portal role here by email — no email delivery needed. Re-running with a new role changes it; it also re-activates a removed account." onSubmit={save} payload={{action:"grant-role-by-email"}}><label>Email<input name="email" type="email" required placeholder="person@example.com"/></label><label>Complete name<input name="completeName" placeholder="Optional"/></label><label>Role<select name="roleCode">{ROLE_OPTIONS.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label></ConfigForm>}
    {section==="users"&&<ConfigForm title="Invite employee account" text="Sends an email invite and links the login to an employee record. Requires email/SMTP to be configured in Supabase." onSubmit={save} payload={{action:"invite-user"}}><label>Employee<select name="employeeId" required><option value="">Select employee</option>{data.employees.map(e=><option key={e.id} value={e.id} disabled={Boolean(e.profile_id)}>{e.complete_name} - {e.position}{e.profile_id?" (account linked)":""}</option>)}</select></label><label>Complete name<input name="completeName" required/></label><label>Email<input name="email" type="email" required/></label><label>Role<select name="roleCode"><option value="cashier">Cashier</option><option value="admin">Admin</option><option value="accounting">Accounting</option><option value="registration">Registration</option><option value="training_operations">Training Operations</option><option value="hr">HR</option><option value="instructor">Instructor</option></select></label></ConfigForm>}
    {section==="users"&&<ConfigForm title="Send password-reset email" text="Emails a secure reset link so the user sets their own password. Passwords are never stored or shown in the portal." onSubmit={save} payload={{action:"reset-password"}}><label>Account email<input name="email" type="email" required placeholder="staff@example.com"/></label></ConfigForm>}
    {section==="users"&&<UserAccounts data={data} onSubmit={save}/>}
    {section==="payment modes"&&<><ConfigForm title="Add payment mode" text="Admin-defined modes become available to Cashier workflows." onSubmit={save} payload={{action:"payment-method",requiresReference:false,allowsProof:true}}><label>Name<input name="name" required/></label><label className="portal-check"><input name="requiresReference" type="checkbox"/><span>Require transaction reference</span></label><label className="portal-check"><input name="allowsProof" type="checkbox" defaultChecked/><span>Allow screenshot proof</span></label></ConfigForm><ConfigList values={data.paymentMethods.map(x=>`${x.name}${x.requires_reference?" - reference required":""}`)}/></>}
    {section==="partners"&&<><ConfigForm title="Add training-center partner" text="Partner centers remain internal and can receive endorsed course offers." onSubmit={save} payload={{action:"partner"}}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email"/></label><label>Mobile<input name="mobile"/></label></ConfigForm><ConfigList values={data.partners.map(x=>x.name)}/></>}
    {section==="marketing agencies"&&<><ConfigForm title="Add marketing agency" text="Agency attribution is preserved on trainee records for future commission reporting." onSubmit={save} payload={{action:"marketing-agency"}}><label>Agency name<input name="name" required/></label><label>Contact person<input name="contactName"/></label><label>Email<input name="email" type="email"/></label><label>Mobile<input name="mobile"/></label></ConfigForm><ConfigList values={data.agencies.map(x=>x.name)}/></>}
    {section==="courses"&&<CourseForm data={data} onSubmit={save}/>} {section==="endorsed rates"&&<OfferForm data={data} onSubmit={save}/>} </div>}

function ConfigForm({title,text,payload,onSubmit,children}:{title:string;text:string;payload:Record<string,unknown>;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;children:React.ReactNode}){return <form className="portal-form config-form portal-panel" onSubmit={onSubmit}><input type="hidden" name="payload" value={JSON.stringify(payload)}/><div className="full"><h2>{title}</h2><p>{text}</p></div>{children}<div className="portal-form-actions full"><button className="portal-primary">Save</button></div></form>}
function ConfigList({values}:{values:string[]}){return <div className="config-list portal-panel">{values.length?values.map(value=><span key={value}>{value}</span>):<p>No records yet.</p>}</div>}
function UserAccounts({data,onSubmit}:{data:Data;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){
  return <div className="config-form portal-panel"><div className="full"><h2>Existing accounts</h2><p>Change a staff member&apos;s portal role — e.g. set an account to Cashier or Registration. Passwords are managed only through the reset email above.</p></div>
    <div className="portal-table full"><table><thead><tr><th>Account</th><th>Current role</th><th>Set role</th></tr></thead><tbody>
      {data.users.map(u=><tr key={u.id}><td><strong>{u.completeName||u.email}</strong><small>{u.email}{u.position?` · ${u.position}`:""}{u.accountState==="Invited"?" · invited":""}{u.accountState==="Deactivated"?" · removed":""}</small></td><td>{u.roles.map(r=>ROLE_OPTIONS.find(o=>o[0]===r)?.[1]??r).join(", ")||"—"}</td>
        <td><div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}><form onSubmit={onSubmit} style={{display:"flex",gap:6,alignItems:"center"}}><input type="hidden" name="payload" value={JSON.stringify({action:"set-user-role",userId:u.id})}/><select name="roleCode" defaultValue={u.roles[0]??"cashier"} aria-label={`Role for ${u.email}`} style={{padding:"6px 8px"}}>{ROLE_OPTIONS.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select><button className="portal-primary" type="submit" style={{padding:"6px 12px"}}>Update</button></form><form onSubmit={onSubmit} style={{display:"inline-block"}}><input type="hidden" name="payload" value={JSON.stringify({action:"remove-user",userId:u.id})}/><button className="ghost-button" type="submit" style={{padding:"6px 12px",color:"#b3261e",borderColor:"#e7b7b2"}} onClick={e=>{if(!confirm(`Remove portal access for ${u.email}? Their Supabase login stays, but all roles are revoked.`))e.preventDefault()}}>Remove</button></form></div></td></tr>)}
      {!data.users.length&&<tr><td colSpan={3}><span className="portal-empty-copy">No portal accounts yet — invite one above.</span></td></tr>}
    </tbody></table></div></div>;
}
function CourseForm({data,onSubmit}:{data:Data;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const [id,setId]=useState(""),course=data.courses.find(c=>c.id===id);return <ConfigForm title="Create or update a course" text="Price and duration changes apply only to future enrollments; historical enrollment snapshots stay unchanged." onSubmit={onSubmit} payload={{action:"course",...(id?{id}:{}),priceCentavos:0,durationDays:1}}><label className="full">Existing course<select value={id} onChange={e=>setId(e.target.value)}><option value="">Create new course</option>{data.courses.map(c=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></label><label>Code<input name="code" required defaultValue={course?.code} key={`${id}-code`}/></label><label>Name<input name="name" required defaultValue={course?.name} key={`${id}-name`}/></label><label>Category<select name="categoryId" required defaultValue={course?.category_id} key={`${id}-cat`}>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Delivery type<select name="deliveryType" defaultValue={course?.delivery_type??"In-House"} key={`${id}-delivery`}><option>In-House</option><option>Partner or Endorsed</option></select></label><label>Duration label<input name="durationLabel" required defaultValue={course?.duration_label} key={`${id}-duration`}/></label><label>Duration days<input name="durationDays" type="number" step="0.5" min="0.5" required defaultValue={course?.duration_days??1} key={`${id}-days`}/></label><label>Mode<input name="mode" required defaultValue={course?.training_mode??"In-person"} key={`${id}-mode`}/></label><label>Price (PHP)<input name="priceCentavos" type="number" step="0.01" min="0" required defaultValue={(course?.standard_price_centavos??0)/100} key={`${id}-price`}/></label></ConfigForm>}
function OfferForm({data,onSubmit}:{data:Data;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const [id,setId]=useState(""),offer=data.offers.find(o=>o.id===id);return <ConfigForm title="Update endorsed offer" text="Rate changes are audited and apply only to future enrollments." onSubmit={onSubmit} payload={{action:"offer-rate",id,trainingFeeCentavos:0,rebateCentavos:0}}><label className="full">Offer<select required value={id} onChange={e=>setId(e.target.value)}><option value="">Select offer</option>{data.offers.map(o=><option key={o.id} value={o.id}>{one(o.partner_centers)?.name} - {one(o.courses)?.name}</option>)}</select></label><label>Duration<input name="durationLabel" required defaultValue={offer?.duration_label} key={`${id}-duration`}/></label><label>Training fee (PHP)<input name="trainingFeeCentavos" type="number" step="0.01" min="0" required defaultValue={(offer?.training_fee_centavos??0)/100} key={`${id}-fee`}/></label><label>New Wave rebate (PHP)<input name="rebateCentavos" type="number" step="0.01" min="0" required defaultValue={(offer?.rebate_centavos??0)/100} key={`${id}-rebate`}/></label></ConfigForm>}
