"use client";
import { FormEvent,useEffect,useState } from "react";

type Data={paymentMethods:{id:string;name:string;requires_reference:boolean}[];agencies:{id:string;name:string}[];partners:{id:string;name:string}[];courses:{id:string;code:string;name:string;category_id:string;delivery_type:"In-House"|"Partner or Endorsed";duration_label:string;duration_days:number;training_mode:string;standard_price_centavos:number}[];offers:{id:string;duration_label:string;training_fee_centavos:number;rebate_centavos:number;partner_centers?:{name:string}|{name:string}[];courses?:{name:string}|{name:string}[]}[];categories:{id:string;name:string}[];employees:{id:string;complete_name:string;position:string;work_email?:string|null;profile_id?:string|null}[];users:{id:string;email:string;completeName:string;accountState:string;roles:string[];position:string|null}[]};
// The seven portal roles (owner, 9 Oct 2026).
const ROLE_OPTIONS:[string,string][]=[["registration","Registration"],["cashier","Cashier"],["accounting","Accounting"],["releasing_officer","Releasing Officer"],["mismo_officer","MISMO Compliance Officer"],["admin_assistant","Admin Assistant"],["admin","Admin"]];
const one=<T,>(v:T|T[]|null|undefined)=>Array.isArray(v)?v[0]:v;
export function AdminConfiguration({catalog=[]}:{catalog?:{key:string;label:string;node:React.ReactNode}[]}={}){const [data,setData]=useState<Data|null>(null),[section,setSection]=useState("users"),[message,setMessage]=useState(""),[debug,setDebug]=useState<{userId:string|null;email:string|null;roles:string[];totalCookies?:number;authCookies?:string[]}|undefined>();async function load(){const response=await fetch("/api/admin/configuration",{cache:"no-store"}),body=await response.json();if(response.ok)setData(body);else{setMessage(body.error);setDebug(body.debug)}}useEffect(()=>{void load()},[]);async function post(payload:Record<string,unknown>,done="Saved."){setMessage("");const response=await fetch("/api/admin/configuration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();setMessage(response.ok?done:body.error??"Could not save.");if(response.ok)await load();return response.ok}async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");const form=new FormData(event.currentTarget),payload=JSON.parse(String(form.get("payload"))) as Record<string,unknown>;for(const [key,value] of form.entries())if(key!=="payload")payload[key]=value;for(const key of ["requiresReference","allowsProof"])if(key in payload)payload[key]=form.get(key)==="on";for(const key of ["priceCentavos","trainingFeeCentavos","rebateCentavos"])if(key in payload)payload[key]=Math.round(Number(form.get(key))*100);if("durationDays" in payload)payload.durationDays=Number(form.get("durationDays"));const response=await fetch("/api/admin/configuration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();setMessage(response.ok?"Saved successfully.":body.error??"Could not save.");if(response.ok){event.currentTarget.reset();await load()}}
  if(!data)return <div className="empty-state portal-panel"><span>{message?"⛔":"⚙"}</span><h2>{message?"Can’t load Admin configuration":"Loading Admin configuration…"}</h2><p>{message?(/admin access/i.test(message)?"Your account is signed in but does not have the Admin role. Ask a system administrator to grant it, or set it in Supabase.":message):"Please wait…"}</p>{debug&&<div style={{marginTop:14,padding:"12px 14px",background:"#f4f8fa",border:"1px solid #dbe7ec",borderRadius:8,textAlign:"left",fontSize:12,color:"#405d70",maxWidth:520,marginLeft:"auto",marginRight:"auto"}}><strong style={{display:"block",marginBottom:6}}>Diagnostics for support</strong><div>Signed in as: <code>{debug.email??"— no session —"}</code></div><div>User ID: <code>{debug.userId??"— none —"}</code></div><div>Roles in database: <code>{debug.roles.length?debug.roles.join(", "):"— none —"}</code></div><div>Cookies received by server: <code>{debug.totalCookies??"?"}</code>{debug.authCookies&&debug.authCookies.length>0?<> (auth: <code>{debug.authCookies.join(", ")}</code>)</>:" (no auth cookies)"}</div><div style={{marginTop:6,fontSize:11,color:"#6d8492"}}>{(debug.totalCookies??0)===0?"The server received NO cookies on this request — the session isn’t reaching the API (middleware/cookie issue).":!debug.userId?"Cookies arrived but no valid session — the token is stale; sign out fully and sign in again.":debug.roles.includes("admin")?"Admin role IS present — refresh; if this persists, report it.":"This account has no admin role. Grant admin to this exact user ID in Supabase."}</div></div>}</div>;
  // Sections are picked from a segmented bar (sentence case, no descriptions).
  const sentence=(v:string)=>v.charAt(0).toUpperCase()+v.slice(1);
  const tabs=[{key:"users",label:"User accounts"},{key:"courses",label:"Course fees"},...catalog.map(c=>({key:c.key,label:sentence(c.label)})),{key:"endorsed rates",label:"Endorsed rates"},{key:"partners",label:"Partner centers"}];
  return <div className="admin-config"><div className="cx-seg config-seg" role="tablist">{tabs.map(t=><button key={t.key} type="button" role="tab" aria-selected={section===t.key} className={section===t.key?"on":""} onClick={()=>{setSection(t.key);setMessage("")}}>{t.label}</button>)}</div>{message&&<p className="form-message">{message}</p>}
    {section==="users"&&<UserAccounts data={data} onSubmit={save} post={post}/>}
    {section==="partners"&&<><ConfigForm title="Add Partner Center" text="Partner centers remain internal and can receive endorsed course offers." onSubmit={save} payload={{action:"partner"}}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email"/></label><label>Mobile<input name="mobile"/></label></ConfigForm><ConfigList values={data.partners.map(x=>x.name)}/></>}
    {section==="courses"&&<CourseForm data={data} onSubmit={save}/>} {section==="endorsed rates"&&<OfferForm data={data} onSubmit={save}/>}
    {catalog.find(c=>c.key===section)?.node} </div>}

function ConfigForm({title,text,payload,onSubmit,children}:{title:string;text:string;payload:Record<string,unknown>;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;children:React.ReactNode}){return <form className="portal-form config-form portal-panel" onSubmit={onSubmit}><input type="hidden" name="payload" value={JSON.stringify(payload)}/><div className="full"><h2>{title}</h2>{text?null:null}</div>{children}<div className="portal-form-actions full"><button className="portal-primary">Save</button></div></form>}
function ConfigList({values}:{values:string[]}){return <div className="config-list portal-panel">{values.length?values.map(value=><span key={value}>{value}</span>):<p>None yet.</p>}</div>}
type Account=Data["users"][number];
/** Employee accounts: the Admin registers, edits, resets passwords for and deletes portal accounts. */
function UserAccounts({data,post}:{data:Data;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;post:(payload:Record<string,unknown>,done?:string)=>Promise<boolean>}){
  const [adding,setAdding]=useState(false),[editing,setEditing]=useState<string|null>(null),[resetting,setResetting]=useState<string|null>(null),[deleting,setDeleting]=useState<string|null>(null),[showRemoved,setShowRemoved]=useState(false);
  const [form,setForm]=useState({completeName:"",email:"",password:"",position:"",roleCode:"cashier",secondRoleCode:""});
  const [edit,setEdit]=useState({completeName:"",position:"",roleCode:"cashier",secondRoleCode:""});
  // An employee may hold two roles (owner, 9 Oct 2026); the second is optional.
  const secondRoleSelect=(first:string,value:string,set:(v:string)=>void)=><label>Second Role (Optional)<select value={value} onChange={e=>set(e.target.value)}><option value="">None</option>{ROLE_OPTIONS.filter(([code])=>code!==first).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label>;
  const [temp,setTemp]=useState("");
  const roleLabel=(code?:string)=>ROLE_OPTIONS.find(o=>o[0]===code)?.[1]??code??"No role";
  const active=data.users.filter(u=>u.accountState!=="Deactivated"),removed=data.users.filter(u=>u.accountState==="Deactivated");
  const startEdit=(u:Account)=>{setEditing(u.id);setResetting(null);setDeleting(null);setEdit({completeName:u.completeName||"",position:u.position??"",roleCode:u.roles[0]??"cashier",secondRoleCode:u.roles[1]??""})};
  const row=(u:Account)=>{
    if(editing===u.id)return <tr key={u.id}><td colSpan={4}><div className="portal-form acct-edit">
      <label>Complete Name<input value={edit.completeName} onChange={e=>setEdit({...edit,completeName:e.target.value})}/></label>
      <label>Position<input value={edit.position} onChange={e=>setEdit({...edit,position:e.target.value})}/></label>
      <label>Role<select value={edit.roleCode} onChange={e=>setEdit({...edit,roleCode:e.target.value,secondRoleCode:edit.secondRoleCode===e.target.value?"":edit.secondRoleCode})}>{ROLE_OPTIONS.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label>
      {secondRoleSelect(edit.roleCode,edit.secondRoleCode,v=>setEdit({...edit,secondRoleCode:v}))}
      <div className="portal-form-actions full"><button type="button" className="portal-secondary" onClick={()=>setEditing(null)}>Cancel</button><button type="button" className="portal-primary" disabled={edit.completeName.trim().length<2} onClick={()=>void post({action:"update-user",userId:u.id,completeName:edit.completeName,position:edit.position,roleCode:edit.roleCode,secondRoleCode:edit.secondRoleCode||null},"Account updated.").then(ok=>{if(ok)setEditing(null)})}>Save Changes</button></div>
    </div></td></tr>;
    return <tr key={u.id}>
      <td><strong>{u.completeName||u.email}</strong><small className="lc">{u.email}</small></td>
      <td>{u.position||"—"}</td>
      <td>{u.accountState==="Deactivated"?<span className="portal-badge cancelled">Deleted</span>:<span className="acct-roles">{(u.roles.length?u.roles:[undefined]).slice(0,2).map((r,i)=><span key={r??i} className="portal-badge active">{roleLabel(r)}</span>)}</span>}</td>
      <td><div className="acct-actions">
        {u.accountState==="Deactivated"?<button type="button" className="portal-secondary" onClick={()=>void post({action:"restore-user",userId:u.id,roleCode:"cashier"},"Account restored as Cashier. Change the role with Edit.")}>Restore</button>:<>
          <button type="button" className="portal-secondary" onClick={()=>startEdit(u)}>Edit</button>
          <button type="button" className="portal-secondary" onClick={()=>{setResetting(resetting===u.id?null:u.id);setDeleting(null);setTemp("")}}>Reset Password</button>
          <button type="button" className="portal-secondary acct-danger" onClick={()=>{setDeleting(deleting===u.id?null:u.id);setResetting(null)}}>Delete</button></>}
      </div>
      {resetting===u.id&&<div className="acct-panel"><label>Temporary Password<input type="text" autoComplete="new-password" value={temp} onChange={e=>setTemp(e.target.value)} placeholder="At least 8 characters"/></label><div className="acct-actions"><button type="button" className="portal-primary" disabled={temp.length<8} onClick={()=>void post({action:"set-password",userId:u.id,password:temp},"Temporary password set. Give it to the employee privately.").then(ok=>{if(ok){setResetting(null);setTemp("")}})}>Set Password</button><button type="button" className="portal-secondary" onClick={()=>void post({action:"reset-password",email:u.email},"Reset link emailed.").then(ok=>{if(ok)setResetting(null)})}>Email Reset Link</button></div></div>}
      {deleting===u.id&&<div className="acct-panel acct-confirm"><span>Delete this account? The employee can no longer sign in. Their past records stay.</span><div className="acct-actions"><button type="button" className="portal-secondary" onClick={()=>setDeleting(null)}>Cancel</button><button type="button" className="portal-primary acct-danger-fill" onClick={()=>void post({action:"delete-user",userId:u.id},"Account deleted.").then(ok=>{if(ok)setDeleting(null)})}>Delete Account</button></div></div>}
      </td></tr>;
  };
  return <div className="acct">
    <section className="portal-panel cx-panel"><div className="panel-heading"><div><h2>Employee Accounts</h2></div><button type="button" className="portal-primary" onClick={()=>setAdding(!adding)}>{adding?"Close":"Add Employee Account"}</button></div>
      {adding&&<div className="portal-form cx-formpad">
        <label>Complete Name<input value={form.completeName} onChange={e=>setForm({...form,completeName:e.target.value})}/></label>
        <label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>
        <label>Temporary Password<input type="text" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters"/></label>
        <label>Position<input value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></label>
        <label>Role<select value={form.roleCode} onChange={e=>setForm({...form,roleCode:e.target.value,secondRoleCode:form.secondRoleCode===e.target.value?"":form.secondRoleCode})}>{ROLE_OPTIONS.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label>
        {secondRoleSelect(form.roleCode,form.secondRoleCode,v=>setForm({...form,secondRoleCode:v}))}
        <div className="portal-form-actions full"><button type="button" className="portal-primary" disabled={form.completeName.trim().length<2||!form.email.includes("@")||form.password.length<8} onClick={()=>void post({action:"create-user",completeName:form.completeName.trim(),email:form.email.trim(),password:form.password,position:form.position.trim()||undefined,roleCode:form.roleCode,secondRoleCode:form.secondRoleCode||null},"Account created. Give the temporary password to the employee privately.").then(ok=>{if(ok){setForm({completeName:"",email:"",password:"",position:"",roleCode:"cashier",secondRoleCode:""});setAdding(false)}})}>Create Account</button></div>
      </div>}
      <div className="portal-table"><table><thead><tr><th>Employee</th><th>Position</th><th>Roles</th><th className="r">Actions</th></tr></thead><tbody>
        {active.map(row)}
        {!active.length&&<tr><td colSpan={4}><span className="portal-empty-copy">No employee accounts yet.</span></td></tr>}
        {showRemoved&&removed.map(row)}
      </tbody></table></div>
      {removed.length>0&&<div className="acct-foot"><button type="button" className="ghost-button" onClick={()=>setShowRemoved(!showRemoved)}>{showRemoved?"Hide deleted accounts":`Show deleted accounts (${removed.length})`}</button></div>}
    </section>
  </div>;
}
function CourseForm({data,onSubmit}:{data:Data;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const [id,setId]=useState(""),course=data.courses.find(c=>c.id===id);return <ConfigForm title="Course Fees" text="Price and duration changes apply only to future enrollments; historical enrollment snapshots stay unchanged." onSubmit={onSubmit} payload={{action:"course",...(id?{id}:{}),priceCentavos:0,durationDays:1}}><label className="full">Existing Course<select value={id} onChange={e=>setId(e.target.value)}><option value="">New Course</option>{data.courses.map(c=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></label><label>Code<input name="code" required defaultValue={course?.code} key={`${id}-code`}/></label><label>Name<input name="name" required defaultValue={course?.name} key={`${id}-name`}/></label><label>Category<select name="categoryId" required defaultValue={course?.category_id} key={`${id}-cat`}>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Delivery Type<select name="deliveryType" defaultValue={course?.delivery_type??"In-House"} key={`${id}-delivery`}><option>In-House</option><option>Partner or Endorsed</option></select></label><label>Duration Label<input name="durationLabel" required defaultValue={course?.duration_label} key={`${id}-duration`}/></label><label>Duration Days<input name="durationDays" type="number" step="0.5" min="0.5" required defaultValue={course?.duration_days??1} key={`${id}-days`}/></label><label>Mode<input name="mode" required defaultValue={course?.training_mode??"In-person"} key={`${id}-mode`}/></label><label>Price (PHP)<input name="priceCentavos" type="number" step="0.01" min="0" required defaultValue={(course?.standard_price_centavos??0)/100} key={`${id}-price`}/></label></ConfigForm>}
function OfferForm({data,onSubmit}:{data:Data;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const [id,setId]=useState(""),offer=data.offers.find(o=>o.id===id);return <ConfigForm title="Endorsed Rates" text="Rate changes are audited and apply only to future enrollments." onSubmit={onSubmit} payload={{action:"offer-rate",id,trainingFeeCentavos:0,rebateCentavos:0}}><label className="full">Offer<select required value={id} onChange={e=>setId(e.target.value)}><option value="">Select Offer</option>{data.offers.map(o=><option key={o.id} value={o.id}>{one(o.partner_centers)?.name} - {one(o.courses)?.name}</option>)}</select></label><label>Duration<input name="durationLabel" required defaultValue={offer?.duration_label} key={`${id}-duration`}/></label><label>Training Fee (PHP)<input name="trainingFeeCentavos" type="number" step="0.01" min="0" required defaultValue={(offer?.training_fee_centavos??0)/100} key={`${id}-fee`}/></label><label>New Wave Rebate (PHP)<input name="rebateCentavos" type="number" step="0.01" min="0" required defaultValue={(offer?.rebate_centavos??0)/100} key={`${id}-rebate`}/></label></ConfigForm>}
