"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { IN_HOUSE_COURSES } from "@/lib/in-house-catalog";

type Draft={firstName:string;middleName:string;lastName:string;suffix:string;srn:string;email:string;presentAddress:string;mobile:string;placeOfBirth:string;birthDate:string;rank:string;company:string;emergencyContactName:string;emergencyContactMobile:string;courseCode:string;scheduleId:string;termsAccepted:boolean};
type Schedule={id:string;label:string;availableSlots:number};
const empty:Draft={firstName:"",middleName:"",lastName:"",suffix:"",srn:"",email:"",presentAddress:"",mobile:"",placeOfBirth:"",birthDate:"",rank:"",company:"",emergencyContactName:"",emergencyContactMobile:"",courseCode:"",scheduleId:"",termsAccepted:false};
const steps=["Personal information","Course and schedule","Review and terms"];

export function RegistrationForm(){
  const [draft,setDraft]=useState<Draft>(empty),[step,setStep]=useState(0),[schedules,setSchedules]=useState<Schedule[]>([]),[loadingSchedules,setLoadingSchedules]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState(""),[reference,setReference]=useState("");
  const course=useMemo(()=>IN_HOUSE_COURSES.find(item=>item.code===draft.courseCode),[draft.courseCode]);
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}));
  useEffect(()=>{if(!draft.courseCode){setSchedules([]);return}const controller=new AbortController();setLoadingSchedules(true);fetch(`/api/public/schedules?courseCode=${encodeURIComponent(draft.courseCode)}`,{signal:controller.signal}).then(response=>response.json()).then(body=>setSchedules(body.schedules??[])).catch(()=>setSchedules([])).finally(()=>setLoadingSchedules(false));return()=>controller.abort()},[draft.courseCode]);
  const personalValid=draft.firstName.trim().length>=2&&draft.lastName.trim().length>=2&&draft.email.includes("@")&&draft.presentAddress.trim().length>=8&&draft.mobile.replace(/\D/g,"").length>=7&&draft.placeOfBirth.trim().length>=2&&Boolean(draft.birthDate)&&draft.rank.trim().length>=2&&draft.emergencyContactName.trim().length>=2&&draft.emergencyContactMobile.replace(/\D/g,"").length>=7;
  const scheduleValid=Boolean(course&&draft.scheduleId);
  async function submit(){if(!course)return;setSubmitting(true);setError("");try{const body=new FormData();for(const [key,value] of Object.entries(draft))if(key!=="termsAccepted")body.set(key,String(value));body.set("courseName",course.course);body.set("termsAccepted","on");const response=await fetch("/api/public/registrations",{method:"POST",body});const result=await response.json();if(!response.ok)throw new Error(result.error??"Registration could not be submitted.");setReference(result.reference)}catch(e){setError(e instanceof Error?e.message:"Registration could not be submitted.")}finally{setSubmitting(false)}}
  if(reference)return <div className="reg-card reg-success"><span className="success-mark">✓</span><h2>Registration and trainee account created</h2><p>Your details, enrollment, selected schedule, and accepted terms were saved. Check your email for the trainee-account activation link.</p><div className="reference-block"><span>Registration reference</span><strong>{reference}</strong></div><div className="reg-success-actions"><Link className="button button-primary" href="/trainee">Open trainee portal</Link><Link className="button button-secondary" href="/registration-search">Check status</Link></div></div>;
  return <div className="reg-card"><ol className="wizard-steps">{steps.map((label,index)=><li key={label} className={index===step?"current":index<step?"done":""}><span>{index<step?"✓":index+1}</span>{label}</li>)}</ol>{error&&<p className="form-message" role="alert">{error}</p>}
    {step===0&&<section className="wizard-panel"><h2>Official trainee information</h2><p className="wizard-hint">These details automatically fill your admission form, account, invoices, receipts, instructions, and certificates.</p><div className="reg-grid">
      <Field label="First name*"><input value={draft.firstName} onChange={e=>set("firstName",e.target.value)} autoComplete="given-name"/></Field><Field label="Middle name"><input value={draft.middleName} onChange={e=>set("middleName",e.target.value)} autoComplete="additional-name"/></Field>
      <Field label="Last name*"><input value={draft.lastName} onChange={e=>set("lastName",e.target.value)} autoComplete="family-name"/></Field><Field label="Suffix"><input value={draft.suffix} onChange={e=>set("suffix",e.target.value)} placeholder="Jr., Sr., III"/></Field>
      <Field label="SRN (MISMO)"><input value={draft.srn} onChange={e=>set("srn",e.target.value.toUpperCase())}/></Field><Field label="Email address*"><input type="email" value={draft.email} onChange={e=>set("email",e.target.value)} autoComplete="email"/></Field>
      <Field label="Present address*" wide><input value={draft.presentAddress} onChange={e=>set("presentAddress",e.target.value)} autoComplete="street-address"/></Field><Field label="Contact number*"><input value={draft.mobile} onChange={e=>set("mobile",e.target.value)} inputMode="tel" autoComplete="tel"/></Field>
      <Field label="Place of birth*"><input value={draft.placeOfBirth} onChange={e=>set("placeOfBirth",e.target.value)}/></Field><Field label="Date of birth*"><input type="date" value={draft.birthDate} max={new Date().toISOString().slice(0,10)} onChange={e=>set("birthDate",e.target.value)}/></Field>
      <Field label="Rank*"><input value={draft.rank} onChange={e=>set("rank",e.target.value)}/></Field><Field label="Company"><input value={draft.company} onChange={e=>set("company",e.target.value)}/></Field>
      <Field label="Emergency contact person*"><input value={draft.emergencyContactName} onChange={e=>set("emergencyContactName",e.target.value)}/></Field><Field label="Emergency contact number*"><input value={draft.emergencyContactMobile} onChange={e=>set("emergencyContactMobile",e.target.value)} inputMode="tel"/></Field>
    </div></section>}
    {step===1&&<section className="wizard-panel"><h2>Select a prepared schedule</h2><p className="wizard-hint">Only New Wave STCW and In-House batches published by the Scheduler are available.</p><div className="reg-grid"><Field label="Course*" wide><select value={draft.courseCode} onChange={e=>{set("courseCode",e.target.value);set("scheduleId","")}}><option value="">Select course</option>{IN_HOUSE_COURSES.map(item=><option key={item.id} value={item.code}>{item.code} - {item.course}</option>)}</select></Field></div>{course&&<div className="course-summary"><div><span>Duration</span><strong>{course.duration}</strong></div><div><span>Delivery</span><strong>{course.modality}</strong></div><div><span>Category</span><strong>{course.category}</strong></div></div>}{loadingSchedules&&<p className="wizard-hint">Loading available schedules…</p>}{!loadingSchedules&&course&&schedules.length===0&&<div className="reg-notice"><strong>No published schedule is available</strong><p>Please choose another course or contact New Wave.</p></div>}<div className="schedule-picker">{schedules.map(item=><button key={item.id} type="button" className={`schedule-option ${draft.scheduleId===item.id?"selected":""}`} onClick={()=>set("scheduleId",item.id)}><span className="schedule-body"><strong>{item.label}</strong><small>{item.availableSlots} of 24 slots available</small></span></button>)}</div></section>}
    {step===2&&<section className="wizard-panel"><h2>Review and accept the official terms</h2><dl className="review-list">{[["Name",`${draft.firstName} ${draft.middleName} ${draft.lastName} ${draft.suffix}`.replace(/\s+/g," ").trim()],["SRN",draft.srn||"Not provided"],["Email",draft.email],["Contact",draft.mobile],["Address",draft.presentAddress],["Birth",`${draft.placeOfBirth} - ${draft.birthDate}`],["Rank / Company",`${draft.rank}${draft.company?` / ${draft.company}`:""}`],["Emergency contact",`${draft.emergencyContactName} - ${draft.emergencyContactMobile}`],["Course",course?.course??""],["Schedule",schedules.find(item=>item.id===draft.scheduleId)?.label??""]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="terms-preview"><img src="/document-templates/terms-and-conditions.png" alt="New Wave Maritime Terms and Conditions"/></div><label className="consent-row"><input type="checkbox" checked={draft.termsAccepted} onChange={e=>set("termsAccepted",e.target.checked)}/><span>I have read and agree to the active New Wave Maritime Terms and Conditions. This acceptance will be recorded with my admission and trainee account.</span></label></section>}
    <div className="wizard-actions"><button className="button button-secondary" type="button" disabled={step===0||submitting} onClick={()=>setStep(current=>Math.max(0,current-1))}>Back</button>{step<2?<button className="button button-primary" type="button" disabled={step===0?!personalValid:!scheduleValid} onClick={()=>setStep(current=>current+1)}>Continue</button>:<button className="button button-primary" type="button" disabled={!draft.termsAccepted||submitting} onClick={()=>void submit()}>{submitting?"Creating your account…":"Submit registration"}</button>}</div>
  </div>
}

function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"span-2":""}>{label}{children}</label>}
