import ExcelJS from "exceljs";
import { z } from "zod";
import { requireStaff } from "@/lib/security";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const querySchema=z.object({from:z.string().date(),to:z.string().date(),report:z.enum(["payments","enrollments","expenses","attendance"])});
const first=<T,>(value:T|T[]|null|undefined):T|null=>Array.isArray(value)?value[0]??null:value??null;
export async function GET(request:Request){const staff=await requireStaff();if(!staff)return new Response("Not authorized",{status:403});try{const query=querySchema.parse(Object.fromEntries(new URL(request.url).searchParams)),from=new Date(`${query.from}T00:00:00+08:00`),toDate=new Date(`${query.to}T23:59:59.999+08:00`);if(toDate<from||toDate.getTime()-from.getTime()>366*86400000)throw new Error("Choose a valid date range of up to 366 days.");const financial=["payments","expenses"].includes(query.report);if(financial&&!staff.roleCodes.some(role=>["admin","accounting","cashier"].includes(role)))return new Response("Not authorized for financial reports",{status:403});const db=createSupabaseAdminClient(),workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet(query.report[0].toUpperCase()+query.report.slice(1),{views:[{state:"frozen",ySplit:1}]});let rows:Record<string,unknown>[]=[];
  if(query.report==="payments"){const {data,error}=await db.from("payments").select("payment_number,amount_centavos,method,receiving_account,reference_number,verification_state,received_at,trainees(trainee_number,legal_first_name,legal_last_name)").gte("received_at",from.toISOString()).lte("received_at",toDate.toISOString()).order("received_at");if(error)throw error;rows=(data??[]).map(item=>{const trainee=first(item.trainees);return {Date:item.received_at,Payment:item.payment_number,Trainee:trainee?`${trainee.legal_first_name} ${trainee.legal_last_name}`:"",Trainee_Number:trainee?.trainee_number,Method:item.method,Account:item.receiving_account,Reference:item.reference_number,Verification:item.verification_state,Amount:Number(item.amount_centavos)/100}})}
  else if(query.report==="enrollments"){const {data,error}=await db.from("enrollments").select("enrollment_number,enrollment_status,selling_price_centavos,rebate_centavos,partner_payable_centavos,created_at,trainees(trainee_number,legal_first_name,legal_last_name),courses(code,name),batches(batch_number,starts_on)").gte("created_at",from.toISOString()).lte("created_at",toDate.toISOString()).order("created_at");if(error)throw error;rows=(data??[]).map(item=>{const trainee=first(item.trainees),course=first(item.courses),batch=first(item.batches);return {Date:item.created_at,Enrollment:item.enrollment_number,Trainee:trainee?`${trainee.legal_first_name} ${trainee.legal_last_name}`:"",Trainee_Number:trainee?.trainee_number,Course:`${course?.code??""} ${course?.name??""}`,Batch:batch?.batch_number,Training_Date:batch?.starts_on,Status:item.enrollment_status,Selling_Price:Number(item.selling_price_centavos)/100,Rebate:Number(item.rebate_centavos)/100,Partner_Payable:Number(item.partner_payable_centavos)/100}})}
  else if(query.report==="expenses"){const {data,error}=await db.from("expenses").select("expense_number,payee,category,amount_centavos,purpose,status,created_at").gte("created_at",from.toISOString()).lte("created_at",toDate.toISOString()).order("created_at");if(error)throw error;rows=(data??[]).map(item=>({Date:item.created_at,Expense:item.expense_number,Payee:item.payee,Category:item.category,Purpose:item.purpose,Status:item.status,Amount:Number(item.amount_centavos)/100}))}
  else {const {data,error}=await db.from("attendance_events").select("event_at,event_type,previous_status,new_status,attendance_records(status,method,enrollments(enrollment_number,trainees(trainee_number,legal_first_name,legal_last_name)))").gte("event_at",from.toISOString()).lte("event_at",toDate.toISOString()).order("event_at");if(error)throw error;rows=(data??[]).map(item=>{const record=first(item.attendance_records),enrollment=first(record?.enrollments),trainee=first(enrollment?.trainees);return {Date:item.event_at,Event:item.event_type,Enrollment:enrollment?.enrollment_number,Trainee:trainee?`${trainee.legal_first_name} ${trainee.legal_last_name}`:"",Trainee_Number:trainee?.trainee_number,Method:record?.method,Previous_Status:item.previous_status,New_Status:item.new_status??record?.status}})}
  const headers=rows.length?Object.keys(rows[0]):["No records"];sheet.columns=headers.map(key=>({header:key.replaceAll("_"," "),key,width:Math.max(14,Math.min(36,key.length+8))}));sheet.addRows(rows);sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:headers.length}};sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF123F63"}};for(const column of sheet.columns)if(["Amount","Selling_Price","Rebate","Partner_Payable"].includes(String(column.key)))column.numFmt='₱#,##0.00';await db.from("audit_logs").insert({actor_id:staff.user.id,actor_role:staff.roleCodes[0],action:"report.exported",record_type:query.report,record_id:`${query.from}:${query.to}`,new_values:{from:query.from,to:query.to,row_count:rows.length,format:"xlsx"}});const output=await workbook.xlsx.writeBuffer();return new Response(new Uint8Array(output),{headers:{"content-type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-disposition":`attachment; filename="new-wave-${query.report}-${query.from}-to-${query.to}.xlsx"`}})
}catch(error){return new Response(error instanceof Error?error.message:"Invalid report request.",{status:400})}}
